# Generated by Django 5.0.7 on 2024-07-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0002_transaction_description_transaction_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
